import Head from "next/head";
import Image from "next/image";


export default function About() {
  return (
    <>
      <Head>
        <title>PokeNext - Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="grid grid-cols-1 md:grid-cols-2 gap-4 w-5/6   md:w-4/6">
      <Image className="w-6/6" src="/images/about-image.png" height={400} width={400} alt="dragão charizard de costas"></Image>
      <div className="w-6/6 md:flex md:items-center bg-gray-50 rounded-lg p-5 md:px-10">
        <div>
        <h1 className="text-3xl pb-2 text-stone-800 ">Sobre PokeNext...</h1>
        <p>
            Um mini-projeto pessoal feito em Next.js, 
            o objetivo foi criar um site informativo simples e agradável
            para testar as tecnologias de react e tailwind, além de por
            meus recentes estudos de Nextjs em prática.<br/>
            Tutorial Base: <a className="text-red-700 hover:text-red-500" href="https://youtube.com/playlist?list=PLnDvRpP8BnezfJcfiClWskFOLODeqI_Ft&si=_33KzrKlAT06Ebtb">Curso de Next.js | Matheus Battisti</a>
        </p>
        </div>
      </div>
      </section>
    </>
  );
}