import Poke_Card from "@/components/Poke_Card";
import { Back } from "@/styles/Content.styles";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { BsChevronUp } from "react-icons/bs";

export const Maxpokemons = 251

export async function getStaticProps(){

  const api = 'https://pokeapi.co/api/v2/pokemon'
  
  const response = await fetch(`${api}/?limit=${Maxpokemons}`)
  const data = await response.json()

  data.results.forEach((element:any,index:number) => {
      element.id = index+1
  });

  return{
    props:{
      pokemons: data.results,   
    }
  }
}

export default function Home({pokemons}:any) {
  const [search,setsearch] = useState('')
  const handlesearch = (event:any)=>{
    console.log(search)
    setsearch(event)
    return false
  }
  return (
    <>
      
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <form onSubmit={(e)=>{e.preventDefault()}} className="w-5/6 md:w-3/6">   
          <label className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
          <div className="relative ">
              <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                  <svg className="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                      <path stroke="#C81E1E" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                  </svg>
              </div>
              <input  type="search"
                      id="default-search" 
                      onChange={(event:any)=> handlesearch(event.target.value)} 
                      value={search}
                      itemID="Search"
                      className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-#FFF6FC focus:ring-red-700 focus:border-red-700 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" 
                      placeholder="meowth, gengar, celebi..." 
                      />
              </div>
      </form>
      <ul className="grid p-6 grid-cols-1 md:grid-cols-3  gap-8">
        {pokemons.map((pokemon:any)=>
          {if(search){
            if(pokemon.name.includes(search.toLowerCase())){
              return(
                <li id={pokemon.name} key={pokemon.id}>
                  <Poke_Card pokemon={pokemon}/>
                </li>
              )
            }}else{
              return(
                <li id={pokemon.name} key={pokemon.id}>
                  <Poke_Card pokemon={pokemon}/>
                </li>
              )
            }
          }
        
        )}
      </ul>
      <Back href="#"><BsChevronUp/></Back>
    </>
  );
}
